// tools/corpus/site-style.mjs
//
// One hand-written stylesheet, no dependencies and no external fetch. A webfont
// or a CDN framework would put a third-party runtime dependency in a corpus
// whose own thesis is that neglected things rot: the site must render correctly
// years from now, offline, with nothing to re-resolve.
//
// Editorial register — serif prose at a bounded measure — because the corpus
// sells trustworthiness, and its pages are long-form argument punctuated by
// dense tables. Colour is carried entirely by custom properties so dark mode is
// a redefinition rather than a second set of rules.

const LIGHT = `
  --bg: #fdfdfb;
  --surface: #f4f3ee;
  --fg: #1b1b18;
  --fg-muted: #5c5a52;
  --rule: #dddbd2;
  --accent: #7a2e1d;
  --accent-soft: #f0e6e2;
  --fresh-fg: #1f4620;
  --fresh-bg: #e3efe1;
  --due-fg: #6b4a07;
  --due-bg: #faeecd;
  --expired-fg: #7a1f1f;
  --expired-bg: #f7dfdf;
`;

const DARK = `
  --bg: #16171a;
  --surface: #1f2126;
  --fg: #e8e6e0;
  --fg-muted: #a3a09a;
  --rule: #33353b;
  --accent: #e39480;
  --accent-soft: #2b2320;
  --fresh-fg: #a9d6a6;
  --fresh-bg: #1e2c1e;
  --due-fg: #e8c97a;
  --due-bg: #322a16;
  --expired-fg: #efa3a3;
  --expired-bg: #351d1d;
`;

export function styleSheet() {
  return `/* Generated by tools/corpus/site-style.mjs — edit there, not here. */

:root {${LIGHT}
  --measure: 68ch;
  --serif: "Iowan Old Style", "Palatino Linotype", Palatino, Georgia, serif;
  --sans: system-ui, -apple-system, "Segoe UI", Helvetica, Arial, sans-serif;
  --mono: ui-monospace, SFMono-Regular, Menlo, Consolas, monospace;
}

@media (prefers-color-scheme: dark) {
  :root {${DARK}  }
}

*, *::before, *::after { box-sizing: border-box; }

html { -webkit-text-size-adjust: 100%; }

body {
  margin: 0;
  background: var(--bg);
  color: var(--fg);
  font-family: var(--serif);
  font-size: 1.0625rem;
  line-height: 1.65;
  text-rendering: optimizeLegibility;
}

main {
  max-width: var(--measure);
  /* 16px side gutter at phone width. */
  padding: 0 1rem 6rem;
  margin: 0 auto;
}

/* --- Site chrome ------------------------------------------------------- */

nav.site {
  font-family: var(--sans);
  font-size: 0.8125rem;
  letter-spacing: 0.04em;
  text-transform: uppercase;
  padding: 1.5rem 0 0;
}

nav.site a { color: var(--fg-muted); text-decoration: none; }
nav.site a:hover { color: var(--accent); text-decoration: underline; }

h1 {
  font-size: clamp(1.75rem, 1.2rem + 2.4vw, 2.5rem);
  line-height: 1.15;
  letter-spacing: -0.01em;
  margin: 1.5rem 0 0.5rem;
}

p.summary {
  font-size: 1.1875rem;
  color: var(--fg-muted);
  margin: 0 0 2rem;
  padding-bottom: 1.5rem;
  border-bottom: 1px solid var(--rule);
}

/* --- Freshness banner -------------------------------------------------- */

.freshness {
  background: var(--surface);
  border: 1px solid var(--rule);
  border-left: 3px solid var(--accent);
  border-radius: 2px;
  padding: 0.875rem 1rem;
  margin: 0 0 2rem;
  font-family: var(--sans);
  font-size: 0.875rem;
}

.freshness p { margin: 0; }
.freshness-unknown { border-left-color: var(--due-fg); }

.seed-note {
  margin: 0.625rem 0 0 !important;
  color: var(--fg-muted);
  font-size: 0.8125rem;
  line-height: 1.5;
}

/* The badge is appended at view time; with JS unavailable the facts above
   stand alone and nothing here renders. */
.badge {
  display: inline-block;
  margin-left: 0.5rem;
  padding: 0.1rem 0.5rem;
  border-radius: 999px;
  font-size: 0.75rem;
  font-weight: 600;
  letter-spacing: 0.03em;
  text-transform: uppercase;
  vertical-align: 0.05em;
}

.badge-fresh { background: var(--fresh-bg); color: var(--fresh-fg); }
.badge-due { background: var(--due-bg); color: var(--due-fg); }
.badge-expired { background: var(--expired-bg); color: var(--expired-fg); }

/* --- Applies-to, section nav, sources, related ------------------------- */

.applies-to, .sources, .related { margin: 2.5rem 0; }

.applies-to h2, .sources h2, .related h2, nav.tiers::before {
  font-family: var(--sans);
  font-size: 0.75rem;
  font-weight: 600;
  letter-spacing: 0.08em;
  text-transform: uppercase;
  color: var(--fg-muted);
  margin: 0 0 0.75rem;
  border: 0;
  padding: 0;
}

.applies-to ul, .sources ul, .related ul, nav.tiers ul {
  list-style: none;
  margin: 0;
  padding: 0;
}

.applies-to li, .sources li, .related li {
  font-family: var(--sans);
  font-size: 0.875rem;
  color: var(--fg-muted);
  padding: 0.25rem 0;
  border-bottom: 1px solid var(--rule);
}

.applies-to li:last-child, .sources li:last-child, .related li:last-child {
  border-bottom: 0;
}

.sources a { color: var(--accent); word-break: break-word; }

nav.tiers {
  background: var(--surface);
  border-radius: 2px;
  padding: 1.25rem;
  margin: 2.5rem 0;
}

nav.tiers::before { content: "Sections"; display: block; }

nav.tiers li { margin: 0.2rem 0; }

nav.tiers a {
  font-family: var(--sans);
  font-size: 0.875rem;
  color: var(--fg);
  text-decoration: none;
  border-bottom: 1px solid transparent;
}

nav.tiers a:hover { color: var(--accent); border-bottom-color: var(--accent); }

/* --- Prose ------------------------------------------------------------- */

article h2 {
  font-size: 1.5rem;
  line-height: 1.25;
  margin: 3rem 0 0.25rem;
  padding-bottom: 0.4rem;
  border-bottom: 2px solid var(--fg);
}

article h3 { font-size: 1.1875rem; margin: 2rem 0 0.25rem; }
article h4 { font-size: 1rem; margin: 1.5rem 0 0.25rem; }

/* Scroll-margin so an anchor jump does not hide the heading under nothing;
   it also keeps the heading clear of the viewport edge. */
article :target, article h2, article h3 { scroll-margin-top: 1.5rem; }

article a { color: var(--accent); text-underline-offset: 0.15em; }

article blockquote {
  margin: 1.5rem 0;
  padding: 0.25rem 0 0.25rem 1.25rem;
  border-left: 3px solid var(--rule);
  color: var(--fg-muted);
}

article strong { font-weight: 650; }

/* --- Code -------------------------------------------------------------- */

code, kbd, samp {
  font-family: var(--mono);
  font-size: 0.875em;
}

:not(pre) > code {
  background: var(--accent-soft);
  padding: 0.1em 0.35em;
  border-radius: 3px;
  word-break: break-word;
}

pre {
  background: var(--surface);
  border: 1px solid var(--rule);
  border-radius: 3px;
  padding: 0.875rem 1rem;
  overflow-x: auto;
  font-size: 0.8125rem;
  line-height: 1.5;
}

pre code { background: none; padding: 0; }

/* --- Tables ------------------------------------------------------------ */

/* The comparison table is 9 columns. It scrolls rather than reflowing, so
   cross-row comparison — the only reason the table exists — survives on a
   phone, and the first column stays pinned so a figure is never orphaned
   from the row it describes. */
.table-scroll {
  overflow-x: auto;
  margin: 1.5rem 0;
  border: 1px solid var(--rule);
  border-radius: 3px;
}

table {
  border-collapse: collapse;
  width: 100%;
  font-family: var(--sans);
  font-size: 0.8125rem;
}

th, td {
  padding: 0.5rem 0.75rem;
  text-align: left;
  vertical-align: top;
  border-bottom: 1px solid var(--rule);
  white-space: nowrap;
}

thead th {
  background: var(--surface);
  font-size: 0.6875rem;
  font-weight: 600;
  letter-spacing: 0.05em;
  text-transform: uppercase;
  color: var(--fg-muted);
  position: sticky;
  top: 0;
}

tbody th:first-child, tbody td:first-child {
  position: sticky;
  left: 0;
  background: var(--bg);
  font-weight: 600;
}

/* A provenance sub-row is a single full-width cell, so it IS :first-child and
   would otherwise stick and float over the scrolling columns. */
.provenance td {
  position: static;
  background: var(--surface);
  white-space: normal;
  font-family: var(--sans);
  font-size: 0.75rem;
  color: var(--fg-muted);
  border-bottom: 2px solid var(--rule);
}

.provenance a { color: var(--fg-muted); }
.provenance a:hover { color: var(--accent); }

/* Inline provenance on a corpus:data figure, which sits mid-sentence. */
span.provenance {
  font-family: var(--sans);
  font-size: 0.75rem;
  color: var(--fg-muted);
  white-space: nowrap;
}

/* --- Front page -------------------------------------------------------- */

.method {
  background: var(--surface);
  border-radius: 2px;
  padding: 1.5rem;
  margin: 2rem 0 3rem;
}

.method h2 { margin-top: 0; border: 0; padding: 0; font-size: 1.1875rem; }
.method li { margin: 0.4rem 0; }

form.search { margin: 2rem 0 0.5rem; }

form.search label {
  display: block;
  font-family: var(--sans);
  font-size: 0.75rem;
  font-weight: 600;
  letter-spacing: 0.08em;
  text-transform: uppercase;
  color: var(--fg-muted);
  margin-bottom: 0.4rem;
}

form.search input {
  width: 100%;
  padding: 0.625rem 0.75rem;
  font: inherit;
  font-size: 1rem;
  color: var(--fg);
  background: var(--bg);
  border: 1px solid var(--rule);
  border-radius: 3px;
}

form.search input:focus-visible {
  outline: 2px solid var(--accent);
  outline-offset: 1px;
}

[data-search-results] { list-style: none; margin: 0.5rem 0 0; padding: 0; }

[data-search-results] li {
  padding: 0.4rem 0;
  border-bottom: 1px solid var(--rule);
  font-family: var(--sans);
  font-size: 0.875rem;
}

[data-search-results] a { color: var(--fg); text-decoration: none; }
[data-search-results] a:hover { color: var(--accent); text-decoration: underline; }

.topics { list-style: none; margin: 0; padding: 0; }

.topic { margin: 0 0 2.5rem; }

.topic h2 {
  font-size: 1.25rem;
  margin: 0 0 0.75rem;
  padding-bottom: 0.3rem;
  border-bottom: 1px solid var(--rule);
}

.topic ul { list-style: none; margin: 0; padding: 0; }
.topic li { padding: 0.35rem 0; }

.topic a {
  color: var(--fg);
  text-decoration: none;
  border-bottom: 1px solid transparent;
}

.topic a:hover { color: var(--accent); border-bottom-color: var(--accent); }

/* --- Accessibility ----------------------------------------------------- */

a:focus-visible, input:focus-visible {
  outline: 2px solid var(--accent);
  outline-offset: 2px;
}

@media (prefers-reduced-motion: reduce) {
  * { animation: none !important; transition: none !important; }
}
`;
}
